# Generated by Django 6.0.3 on 2026-03-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="choice_text_en",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="question",
            name="description",
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name="question",
            name="description_en",
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name="question",
            name="question_text_en",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
